# Generated by Django 4.0.6 on 2022-07-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.CharField(max_length=500)),
                ('usernam', models.CharField(max_length=200)),
            ],
        ),
    ]
