# Generated by Django 4.0.6 on 2022-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.CharField(max_length=200),
        ),
    ]
