# Generated by Django 4.0.6 on 2022-07-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0005_alter_followers_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followers',
            new_name='follower',
        ),
    ]
